name = "proud-sun-003e"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "xiaosh-image-bed"

[observability]
enabled = true
